### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sunfeng90** [bytehala/android-mqtt-quickstart#1]
I got this problem"Error:(org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence$2) that doesn't come with an
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:indicate that it is _not_ an inner class.
Error:compiler that did not target the modern .class file format. The recommended
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:this warning is that reflective operations on this class will incorrectly
Error:this warning is that reflective operations on this class will incorrectly
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:indicate that it is _not_ an inner class.
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/eclipse/paho/client/mqttv3/MqttCallback;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_77\bin\java.exe'' finished with non-zero exit value 2
> :app:transformClassesWithDexForDebug FAILED"

**Comment by sunfeng90** [comment]
How to solve it？

**Comment by bytehala** [comment]
Hi, were you able to solve it yet? It might be because you're using Java 8, can you try using Java 7?

**Comment by bytehala** [comment]
Closing issue, as current version compiles on more current versions of Java/Gradle/AS.
