### ISSUE TITLE
Grabbing messages in ConnectionDetailsActivity.java

### ISSUE THREAD

**Issue by duxlo-cruxtech** [bytehala/android-mqtt-quickstart#4]
Hi, first of all, thank you for creating this project. It's been so helpful to learn android while developing an MQTT app.

In ConnectionDetailsActivity.java I am trying to get the messages received from the MQTTCallbackHandler.java.

I believe the code for it resides in:
public void run() {

          connectionDetails.invalidateOptionsMenu();
          ((HistoryFragment) connectionDetails.sectionsPagerAdapter
              .getItem(0)).refresh();

          updateButtons();

        }

I created several logs to figure out where that data is, but I just have been unable to find it.

I tried:
Log.v(((HistoryFragment) connectionDetails.sectionsPagerAdapter
                  .getItem(0)).getArguments().toString(),"Arguments");

but am still unable to figure out where it is.

The goal is to listen to the subscribed message and update the status of a button on the screen.

In the MQTTCallbackHandler, I was able to identify that it is stored in args[0], but when it is passed to c.addAction(messageString) I don't know where it ends up for me to read in ConnectionDetailsActivity.java.

Thank you for your help!

**Comment by bytehala** [comment]
I’ll take a look, note that this app is very old, not up to recent Android standards and I am refactoring it to use AndroidX so do not use the app to learn Android. :) Having said that, there’s definitely an answer to your question. Will get back to you today or tomorrow.

**Comment by duxlo-cruxtech** [comment]
Thanks for the prompt reply! Yes, I did notice some older modules like the pager.

**Comment by bytehala** [comment]
Hi, you were definitely looking in the right place. HistoryFragment just uses the Connection object's history to update its UI. Since you already have a reference to connection, try this in the run() method and see if it works for you:

````
    Spanned[] history = connection.history();
    Log.v("NewMessage", "" + history[history.length -1]); // Will get the latest message
````

Just repurpose it to suit your own requirements.

**Comment by duxlo-cruxtech** [comment]
Thanks so much! That's exactly what I was looking for. I would have never thought of using Spanned.

**Comment by bytehala** [comment]
No worries. Please consider Starring the repo. It helps me out.
